# Generated by Django 6.0 on 2025-12-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для публикации', null=True, upload_to='posts_images/', verbose_name='Изображение'),
        ),
    ]
